import { NextResponse } from 'next/server'
import JSZip from 'jszip'
import { requireAuth, requireScopedAdmin } from '@/lib/auth-helpers'
import { createSupabaseAdmin } from '@/lib/supabase-admin'
import { checkRateLimit, getClientIp } from '@/lib/rate-limit'
import { logAudit } from '@/actions/audit'

export const runtime = 'nodejs'
export const maxDuration = 60

/**
 * GDPR Right to Access (čl. 15): vráti ZIP so všetkými údajmi o userovi.
 * Prístup: target user sám seba, alebo admin/it_admin v scope.
 */
export async function GET(_req: Request, ctx: { params: Promise<{ userId: string }> }) {
  const { userId } = await ctx.params

  // Rate limit (drahá operácia)
  const rl = await checkRateLimit('gdprExport', `gdpr-export:${await getClientIp()}`)
  if (!rl.ok) {
    return NextResponse.json({ error: `Príliš veľa požiadaviek, skús o ${rl.retryAfter}s` }, { status: 429 })
  }

  // Auth: self OR scoped admin
  const selfAuth = await requireAuth()
  if ('error' in selfAuth) return NextResponse.json({ error: selfAuth.error }, { status: 401 })

  const isSelf = selfAuth.user.id === userId
  if (!isSelf) {
    const adminAuth = await requireScopedAdmin(userId)
    if ('error' in adminAuth) return NextResponse.json({ error: adminAuth.error }, { status: 403 })
  }

  const admin = createSupabaseAdmin()

  const [profile, jazdy, dochadzka, dovolenky, cesty, audit] = await Promise.all([
    admin.from('profiles').select('*').eq('id', userId).single(),
    admin.from('jazdy').select('*').eq('user_id', userId),
    admin.from('dochadzka').select('*').eq('user_id', userId),
    admin.from('dovolenky').select('*').eq('user_id', userId),
    admin.from('sluzobne_cesty').select('*').eq('user_id', userId),
    admin.from('audit_log').select('*').eq('user_id', userId),
  ])

  if (!profile.data) {
    return NextResponse.json({ error: 'Užívateľ nenájdený' }, { status: 404 })
  }

  const zip = new JSZip()
  zip.file('README.txt', [
    'GDPR Export — Right to Access (GDPR čl. 15)',
    '',
    `User ID: ${userId}`,
    `Generated: ${new Date().toISOString()}`,
    `Generated by: ${selfAuth.user.id} (${isSelf ? 'self-request' : 'admin-request'})`,
    '',
    'Obsah:',
    '  profile.json       — Základné údaje (meno, email, role, ...)',
    '  jazdy.json         — Knihu jázd',
    '  dochadzka.json     — Záznamy dochádzky',
    '  dovolenky.json     — Žiadosti o dovolenku',
    '  sluzobne-cesty.json — Služobné cesty',
    '  audit-log.json     — Akcie zaznamenané v audit logu',
    '',
    'Poznámka: účtovné záznamy zostávajú u prevádzkovateľa po dobu retencie',
    'podľa zákona č. 431/2002 Z. z. a č. 461/2003 Z. z. (10 rokov), aj keď je',
    'profil neskôr anonymizovaný.',
  ].join('\n'))

  zip.file('profile.json', JSON.stringify(profile.data, null, 2))
  zip.file('jazdy.json', JSON.stringify(jazdy.data || [], null, 2))
  zip.file('dochadzka.json', JSON.stringify(dochadzka.data || [], null, 2))
  zip.file('dovolenky.json', JSON.stringify(dovolenky.data || [], null, 2))
  zip.file('sluzobne-cesty.json', JSON.stringify(cesty.data || [], null, 2))
  zip.file('audit-log.json', JSON.stringify(audit.data || [], null, 2))

  const buffer = await zip.generateAsync({ type: 'nodebuffer' })

  await logAudit('gdpr_export', 'profiles', userId, {
    self: isSelf,
    counts: {
      jazdy: jazdy.data?.length || 0,
      dochadzka: dochadzka.data?.length || 0,
      dovolenky: dovolenky.data?.length || 0,
      cesty: cesty.data?.length || 0,
      audit: audit.data?.length || 0,
    },
  })

  return new Response(new Uint8Array(buffer), {
    status: 200,
    headers: {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="gdpr-export-${userId.slice(0, 8)}-${Date.now()}.zip"`,
      'Cache-Control': 'no-store',
    },
  })
}
